name: Sync to HF Space
on:
  push:
    branches: [ "main" ]
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_USERNAME: your-hf-username
          SPACE_NAME: snodas-melt
        run: |
          git config user.email "actions@github.com"
          git config user.name "github-actions"
          git remote add space https://$HF_USERNAME:$HF_TOKEN@huggingface.co/spaces/$HF_USERNAME/$SPACE_NAME
          git push --force space HEAD:main
